### ISSUE TITLE
Slow GBA Emulation

### ISSUE THREAD

**Issue by MizuhoChan** [pixelcircuits/GBConsole#3]
Hi, not sure how else to get in touch lol.  I see that you can put the gba bios onto the pi's sd card, but what sort of filename does it require?  I use HDR's bios dumper, but the default filename hasn't made any difference.  Nor did gba.bios, which I just felt like trying.

As an aside, could you possibly add sf30 pro bluetooth compatibility?

**Comment by pixelcircuits** [comment]
It should be named "gba_bios.bin". I have a note to specify this in the user guide documentation and should be pushing the update soon. I definitely want to get more controller support, but it's not too high on the priority list. It might actually work right now if you pair it to the Pi manually.

**Comment by MizuhoChan** [comment]
Hey, thanks very much for the reply.  That was the default filename from HDR's bios dump program, so I guess it doesn't run at 100% speed even with the bios?

I'm not sure how to do it, but I will look into how to pair it manually.  Thanks for the idea.

**Comment by pixelcircuits** [comment]
Some games won't run 100%, but most that I tested do. I'll make a note to be less strict on the bios file naming too. Try forcing the gba emulator to lr-gpsp in the settings menu (lr-mgba won't run full speed, but is more perfect emulation). This is also a good way to check if the bios file was successfully found since lr-gpsp won't even boot if it's not there.

**Comment by MizuhoChan** [comment]
Oh, that's good to know as perhaps it's not reading it for some reason, as I'm just getting a black/white screen while trying to boot with gpsp.  I'll try to get another dump and try again.
